### ISSUE TITLE
Actuators mess up randomly.

### ISSUE THREAD

**Issue by TeeriaLLC** [NyxStudios/TShock#1114] opened 2015-09-13 13:17 UTC
So I still do not know whether this is an issues with Terraria or TShock, because I do not see this happening in Terraria Vanilla and (obviously SP).

Basically, actuated blocks mess up for no reason whatsoever and this never happened in 1.2.4.1.
https://i.gyazo.com/4325711597f5c90ea3283c648bdc87af.png

**Comment by TeeriaLLC** [comment] 2015-09-13 13:18
It could also be timer based, because it also seems to happen to blocks which are not actuated but simply attached to a timer.

**Comment by WhiteXZ** [comment] 2015-09-13 13:21
This has been an issue for years, first occurring with activate/inactive stone blocks. As such it's likely a terraria-side issue.

**Comment by TeeriaLLC** [comment] 2015-09-13 13:29
Odd that it happens in certain worlds then, even though I doubt they will fix any of these issues even when 1.3.1 with new mechanics is on the way.

**Comment by ProfessorXZ** [comment] 2016-08-01 08:06
@TeeriaLLC Seeing it's been almost a year since this issue was reported, please confirm it.

**Comment by tlworks** [comment] 2016-08-01 14:01
@ProfessorXZ Still happens but less since the 'lag' has been reduced.

**Comment by ProfessorXZ** [comment] 2016-08-02 12:38
@tlworks Post the reproduction steps, please.

**Comment by nicatronTg** [comment] 2016-10-11 00:09
Closing until reproduction steps are found. If reproduction steps are found, please post them here. If not, this should be fixed by a move to Orion if it's not a Terraria side issue.

**Closed by nicatronTg** 2016-10-11 00:09 UTC
