### ISSUE TITLE
Logic Gates, Logic Sensors, and Weighted Pressure Plates not functioning

### ISSUE THREAD

**Issue by Marcus101RR** [NyxStudios/TShock#1191] opened 2016-05-28 06:49 UTC
This is another generic issue apparently since these are new items to the game, they do not work on multiplayer for tshock. However, in Vanilla the functions work fine. This probably will get fixed as the final release approaches. Just adding it in the notes of issues.

**Comment by Enerdy** [comment] 2016-05-28 18:45
Is this a TShock issue, or a https://github.com/NyxStudios/TerrariaAPI-Server issue?
(did you manage to reproduce it on TSAPI without TShock? Because if so, you should re-issue this at its repo)

**Comment by Enerdy** [comment] 2016-05-28 21:10
![terraria_2016-05-28_22-10-30](https://cloud.githubusercontent.com/assets/3332657/15629995/fe8d1662-2520-11e6-82be-d17e69a8214c.png)
![terraria_2016-05-28_22-10-39](https://cloud.githubusercontent.com/assets/3332657/15629996/fe918fbc-2520-11e6-9083-d0afa82ec68a.png)
![terraria_2016-05-28_22-10-45](https://cloud.githubusercontent.com/assets/3332657/15629997/fe94620a-2520-11e6-99ec-19d777a12733.png)

**Comment by Enerdy** [comment] 2016-05-28 21:30
Status: I made them all placeable, and logic gates seem to work now, but sensors are still not triggering for some reason. Further investigation needed.

**Comment by Enerdy** [comment] 2016-05-29 21:30
Good news: My most recent commits, along with cracker's cherry-on-top-of-the-cake commit, seem to have finally fixed this. I have tested all of the logic gates, with positive results for every of them.

**Comment by Enerdy** [comment] 2016-05-29 21:31
![terraria_also_try_minecraft _2016-05-29_22-29-30](https://cloud.githubusercontent.com/assets/3332657/15636121/0a21977e-25ed-11e6-933e-41de0f5f3004.png)
![terraria_also_try_minecraft _2016-05-29_22-29-36](https://cloud.githubusercontent.com/assets/3332657/15636123/0a6488c2-25ed-11e6-9f0d-afe367a93fd0.png)
![terraria_also_try_minecraft _2016-05-29_22-29-23](https://cloud.githubusercontent.com/assets/3332657/15636122/0a636d48-25ed-11e6-9cb7-a62509a6b235.png)

**Comment by Enerdy** [comment] 2016-05-29 21:32
![terraria_also_try_minecraft _2016-05-29_22-32-18](https://cloud.githubusercontent.com/assets/3332657/15636132/3c4ba582-25ed-11e6-8930-e1f2a40534c8.png)
![terraria_also_try_minecraft _2016-05-29_22-32-30](https://cloud.githubusercontent.com/assets/3332657/15636133/3c5515b8-25ed-11e6-8a29-d7934342c466.png)

**Comment by Enerdy** [comment] 2016-05-29 21:39
Weighted pressure plates still don't work.

**Comment by cracker64** [comment] 2016-05-29 21:57
Weighted pressure plates is actually a Server-API issue and I have a fix for it already.

**Comment by Enerdy** [comment] 2016-05-29 22:25
Thanks for the fix, @cracker64. Will close this once it is merged.

**Closed** 2016-05-30 01:32 UTC
Labels: Confirmed Issue

**Comment by recon88** [comment] 2016-05-31 11:16
May I ask if this fix is included in the latest version? I'm still having this issue after updating.

**Comment by WhiteXZ** [comment] 2016-06-01 01:54
@recon88 normal plates were broken, and will be fixed in our 1.3.1.1 release :)
