### ISSUE TITLE
Information like Metal Detector don't share correctly

### ISSUE THREAD

**Issue by VALLIS-NERIA** [NyxStudios/TShock#1152] opened 2016-01-04 16:32 UTC
I stand aside my teammate and we both belong to red party. He equipped a Metal Detector but I'm not able to get access of the information.

**Comment by Angelyss** [comment] 2016-01-13 09:43
Could not reproduce on 4.3.11; may be 4.3.12 update related:

![2016-01-13_00003](https://cloud.githubusercontent.com/assets/14846414/12290471/e9f3ec40-ba1c-11e5-9aed-c045f4bf6b95.jpg)
![2016-01-13_00004](https://cloud.githubusercontent.com/assets/14846414/12290469/e9f11fe2-ba1c-11e5-8dbc-717c8df41ee4.jpg)
![2016-01-13_00005](https://cloud.githubusercontent.com/assets/14846414/12290470/e9f1fcc8-ba1c-11e5-9f1f-da98bf46ce28.jpg)
![fatp4sx](https://cloud.githubusercontent.com/assets/14846414/12290480/01ee5498-ba1d-11e5-833f-dfaaab7f0533.jpg)

**Comment by Gummin** [comment] 2016-03-01 02:24
Unable to reproduce with 4.3.12.

**Comment by ProfessorXZ** [comment] 2016-09-24 19:05
Can anyone confirm this is still an issue?

**Comment by nicatronTg** [comment] 2016-10-11 01:15
@Patrikkk can you test this issue (since I don't have working Terraria copies laying around)? If not, please immediately tag me to test it.

**Comment by Patrikkk** [comment] 2016-10-11 01:25
This seems to be working just fine. 
You only get the information if you're within 100ft, not over, which is most probably an intended Terraria feature. (Please correct me if I'm wrong).
Feel free to close this.

**Closed** 2016-10-11 01:54 UTC
Labels: Bug?, Improvement, Needs Investigation
