### ISSUE TITLE
Typing /" bypasses the chat handler

### ISSUE THREAD

**Issue by ProfessorXZ** [NyxStudios/TShock#1301] opened 2016-10-14 21:35 UTC
This was mentioned by OFF/tlworks before but was never reported here. Players are able to bypass mutes etc by typing /" in chat. This breaks the whole handler and chat is no longer handled by our hook. If I remember correctly the issue lies in the `ParseParameters(string)` method. I believe the nature of that code is what causes this (keep in mind that I am not 100% sure about this).

**Comment by nicatronTg** [comment] 2016-10-14 23:18
Assuming confirmed, triaging as appropriate.

**Comment by Simon311** [comment] 2016-10-15 03:22
Here's a question you want to ask youself first: is /"heal" working the intended behavior? Is this a legit way of supporting usage of spaces in command names, or this weird bug-feature?

**Comment by Simon311** [comment] 2016-10-15 03:25
Yet another question,  is 
> /         heal             player
working the intended behavior?

**Comment by nicatronTg** [comment] 2016-10-15 03:27
@Simon311 the answer to both of those questions for me is no. I don't know about anyone else, but it violates the principle of least surprise to have something like `/"this"` or `/ this` work.

**Comment by Simon311** [comment] 2016-10-15 03:28
@nicatronTg That means the command's name must be handled separately from command arguments, which is not how we do it at the moment

**Comment by nicatronTg** [comment] 2016-10-15 03:31
@Simon311 not necessarily => I'm just answering your question. The issue at hand here is breaking the handler in unexpected ways, which could be covered while keeping this...strange functionality inside.

**Comment by Simon311** [comment] 2016-10-15 03:51
@nicatronTg What happens in the code is that due to the logic of ParseParameters it returns an empty List for /". Then, HandleCommand reacts to this with a args.Count < 1 check by returning false, which then gets assigned to args.Handled with no additional handling being done.
I see three problems here, contributing to each other. 
The first one is that ParseParameters does behave logically **given that** it does receive a string of command parameters, not command name + command parameters. I do not see any logic in handling the command's name as a parameter.
The second problem is HandleCommand behaving bad here, returning false in this case, when it clearly should not. By the time execution gets to HandleCommand, the checks located before HandleCommand have already made sure that the text consits of at least the command specifier and at least one non-whitespace character, which means that whatever got passed to it will definitely qualify as an attempt to execute a command. Therefore, it should say "Invalid command", etc...
The third problem is the fact that if HandleCommand for some reason returns false (and this issue is the ONLY case when it would do that at all), this value simply gets assigned to args.Handled and NO additional handling is done. This is a design problem, with two possible solutions. Either make HandleCommand void instead of bool and always do args.Handled = true, or add additional handling for this only glorious case and force it to be handled as a chat message instead.

**Comment by Simon311** [comment] 2016-10-15 04:01
@nicatronTg So, the reason I asked whetever those case are supposed to be legit command usage is to clarify how to approach this fix.
The possibilities are:
1) Handle the command's name separately from argument handling, pass only the parameters to ParseParameters, remove args.Count < 1 check. This way every bit of code does what we actually expect it to do.
2) Inform the user that /" is in fact an invalid command and return true. This might not be a good idea in case someone decides to name their command ". The first solution, however, will account for this.
3) Make HandleCommand void instead of bool, replace return false; with return; and always do args.Handled = true. This solution will simply leave the user with no output at all. Once again, this will fail miserably if someone actually makes a /" command.

As you can see, the only solution that actually does make sense is the first one. The rest work, but in a non-beautiful way.

**Comment by nicatronTg** [comment] 2016-10-15 04:10
Well, then solution 1 works for me.

**Comment by Simon311** [comment] 2016-10-15 04:22
@nicatronTg One more concern then. Are there any plugins which use spaces in command names? I definetely hope not.

**Comment by nicatronTg** [comment] 2016-10-15 04:36
I don't believe anyone is that ridiculous, no. Nothing comes to mind that eclectic.

**Closed** 2016-10-16 10:55 UTC
Labels: Confirmed Issue, Hacktoberfest, Pull Request Wanted
