### ISSUE TITLE
Quick stack to nearby chests not working

### ISSUE THREAD

**Issue by CandiedFedora** [NyxStudios/TShock#1290] opened 2016-09-25 22:28 UTC
Hiya, so today I installed Tshock (Newest version as of 26.09.2016) for Terraria 1.3.3.2. Then I was trying to empty my Inventory using Quick Stack to nearby chests but it wasn't working. Here a short clip while in-game: https://www.youtube.com/watch?v=Q5ZrUj0Unm0 I was pressing the button to quick stack at that point but it wasn't working. Hope this is a known issue / there's a fix for this. Thanks!

**Comment by Patrikkk** [comment] 2016-09-25 22:30
Thanks for the report, altho it is a duplicate of :
https://github.com/NyxStudios/TShock/issues/1287

There was a fix for it. Which you can get on the latest bamboo build.
https://bamboo.tshock.co/browse/TERRA-TSHOCK/latest

**Comment by ProfessorXZ** [comment] 2016-09-25 22:31
This issue was reported 2 days ago and was fixed. If you want to you can always download the Bamboo build including the fix from the forums by clicking "Unstable Builds" in the Download tab. Always make sure to check all issues in case it was already fixed, thank you for the report though :)

**Closed** 2016-09-25 22:33 UTC
