### ISSUE TITLE
Rope Coils do not work

### ISSUE THREAD

**Issue by maxtarias** [NyxStudios/TShock#1369] opened 2016-12-30 21:02 UTC
You can create rope coils, but when thrown they disappear on impact, leaving no ropes hung or as items.

**Comment by Marcus101RR** [comment] 2016-12-30 21:16
@maxtarias This issue was fixed here https://github.com/NyxStudios/TShock/issues/1352. You will need to use a compiled version yourself or wait for the next build/release to see the fix.

**Comment by maxtarias** [comment] 2016-12-30 21:21
Okay so I'm kinda dumb to the server config stuff, so how will I make them work in my server?

**Comment by Ijwu** [comment] 2016-12-30 21:23
@maxtarias You've been informed about the state of this fix.

The fix is not currently available in a general-public release. You may go through the effort of obtaining an unstable, bleeding edge, version or compile the code yourself. Until the next release, that will be the only way to see these changes. 

I'm closing this issue seeing as the problem is fixed, but not yet deployed.

**Closed by Ijwu** 2016-12-30 21:23 UTC
