### ISSUE TITLE
When it rains the screen doesn't show rain

### ISSUE THREAD

**Issue by Puremin0rez** [NyxStudios/TShock#949] opened 2015-07-06 06:00 UTC
When it rains, all of the effects of rain occurs (flying fish, umbrella mobs, etc) but the rain isn't visible on screen.

tShock PR2 on Mono 4.0.2

**Comment by tylerjwatson** [comment] 2015-07-06 06:56
As part of TSAPI I did remove references to rain, I might have mistakenly assumed it was just client code.  May have to add it back

**Comment by tylerjwatson** [comment] 2015-07-06 06:57
cc @WhiteXZ do you know of any way that we can turn rain on in the code to test whether this was the case?

**Comment by WhiteXZ** [comment] 2015-07-06 06:58
@tylerjwatson link me the commit and I'll see if I can find any deleted code that may have been relevant

**Comment by tylerjwatson** [comment] 2015-07-06 06:59
commit 621781ea81a3be1bc657d7e4cf065a695c13d829

**Comment by WhiteXZ** [comment] 2015-07-06 07:04
I can see no reason why that commit would break rain on the client end

**Comment by tylerjwatson** [comment] 2015-07-06 07:05
yeah that's what I thought, is there any cases where rain is communicated in a packet anywhere?  couldn't see any from the doc

**Comment by WhiteXZ** [comment] 2015-07-06 07:19
@Puremin0rez can you reproduce this without TShock (i.e., just the terrariaserver build we provide)?

**Comment by Puremin0rez** [comment] 2015-07-06 07:23
I'll go ahead and try it now. Might be a bit before I can get rain to trigger

**Comment by Puremin0rez** [comment] 2015-07-06 23:02
Left the decompiled server (no tshock or server plugins active) running overnight and 3 people said the rain still was not visible on screen, but all effects were in place.

**Comment by WhiteXZ** [comment] 2015-07-07 02:07
This is likely because our WorldInfo packet doesn't work as it should. If you leave then rejoin after it starts raining, you client should(?) start displaying the rain

**Comment by WhiteXZ** [comment] 2015-07-07 02:47
Fixed in latest commit

**Closed by WhiteXZ** 2015-07-07 02:47 UTC
Labels: Confirmed Issue, Mono
