### ISSUE TITLE
disappearing NPC's

### ISSUE THREAD

**Issue by zytho** [NyxStudios/TShock#953] opened 2015-07-06 09:31 UTC
A server with a world generated when 1.3 came out. Had a LOT of NPC's. Some seemed to have disappeared while others seem to have died and not come back. They also have disappeared from the Housing list.

**Comment by WhiteXZ** [comment] 2015-07-06 09:42
@zytho why was this closed? Did you find a cause for the problem?

**Comment by Puremin0rez** [comment] 2015-07-07 03:15
Curious as to why this was closed as well - I'm still experiencing this problem.

**Comment by madfunny** [comment] 2015-07-07 10:01
I have NPC's that walk around as normal then suddenly vanish! Where'd they go no able body knows, then they come back across the map. It's magic!  :p

**Comment by arunesh90** [comment] 2015-07-07 11:03
Yeah im experiencing the same problem with all 3 of the pre-releases.

**Comment by WhiteXZ** [comment] 2015-07-07 11:04
Could you remove TShockAPI.dll from your ServerPlugins folder and try to reproduce this issue? Note that you won't have access to TShock's commands during this process

**Comment by alexaaa789** [comment] 2015-07-07 12:40
Besides the disappearing NPCs problem, the NPCs are acting weird too. 

For example, the Angler that lives at ground floor in my world keeps opening the door and walk into my house, then walk out of the house and teleports back to the zombie-proof hole. He just keeps on looping this action.

The NPCs also teleports to a fixed point after a while and when I talk to them.

![capture 2015-07-07 20_24_03](https://cloud.githubusercontent.com/assets/13219519/8546219/6590c73a-24e8-11e5-834d-1c5afbda0885.jpg)

**Comment by arunesh90** [comment] 2015-07-07 17:29
I removed TShockAPI.dll from the folder.
I started the server and saw that the world and things were still normal... until i saw the mechanic npc fighting an enemy and after the enemy was dead she vanished in front of my eyes also from the housing list....

**Comment by arunesh90** [comment] 2015-07-07 17:41
Ummm after some minutes almost all my npc's vanished just like nothing while TShockAPI is gone. When TShockAPI was still installed the vanishing npc's was much slower now its super fast im almost out of npc's even

**Comment by Ijwu** [comment] 2015-07-07 17:52
Confirmed on vanilla.

**Comment by madfunny** [comment] 2015-07-10 22:19
My Nurse NPC is now throwing knives at herself in a loop while also healing herself each time.

Ahh, self destruction.

**Comment by nicatronTg** [comment] 2015-07-10 22:50
@madfunny we'll definitely look into your suicidal nurse for you.

**Comment by AndrioCelos** [comment] 2015-07-16 07:15
Looks like the API broke AI of all projectiles with `aiStyle > 66`, including the nurse's placebo syringes. All the following AI branches are within the `if (this.aiStyle == 66)` branch, and there's another similar error further down.
https://github.com/AndrioCelos/TerrariaAPI-Server/commit/86c84cde8e4bd17ad76778b79e3e974570a959d8 fixes it. The commit looks big because I dedented a lot of lines.

**Closed** 2015-07-20 13:04 UTC
Labels: Confirmed Issue
