### ISSUE TITLE
Wyverns despawn

### ISSUE THREAD

**Issue by silentnj** [NyxStudios/TShock#1297] opened 2016-10-12 14:17 UTC
Hello there. so i've been playing terraria with a few friends on my tshock server
and the wyverns seem to be bugged and despawn randomly.

**Comment by Ijwu** [comment] 2016-10-12 19:42
Is anyone capable of reproducing this issue? Is this a known bug?

**Comment by ProfessorXZ** [comment] 2016-10-12 20:17
@Ijwu Yes it is known, we had a lot reports in the past few months. I was able to confirm this, but this is not a TShock issue. It is an issue with our decompiled server. Same thing goes for Eater of Worlds despawns. Either the decompiler adds code which would be extremly weird or something was messed up during the diff. Our server checks whether there are players in the Corruption zone, and it there are none the Eater of Worlds will despawn, while this does not seem to be the case in the vanilla server. I'd guess something similar is causing this, might be an AI issue too. As this is not a TShock issue I feel like you should close this and move to the TSAPI repo.

**Comment by Ijwu** [comment] 2016-10-12 20:19
Okay. This seems like an issue that may be fixed just by moving to Orion in the future. Is it possible to find a solution for this right now in a feasible/reasonable amount of effort? @ProfessorXZ

**Comment by ProfessorXZ** [comment] 2016-10-12 21:19
I never got to finding the reason of Wyverns despawning, I think I didn't find anything at the time. The best solution would most likely be diff the file again and see what's wrong.

**Comment by nicatronTg** [comment] 2016-10-12 21:43
Honestly, unless I start bribing @Enerdy to work on AAA, @tylerjwatson to start pushing the ball on magical development, @MarioE to quit MIT, and @WhiteXZ to move to Silicon Valley, Orion is still a couple months out at least.

So, while this will probably be fixed in Orion, I'm gonna go throw this in the API repo.

**Comment by nicatronTg** [comment] 2016-10-12 21:45
Closing as it's now covered in API.

**Closed by nicatronTg** 2016-10-12 21:45 UTC
Labels: Confirmed Issue

**Comment by nicatronTg** [comment] 2016-10-13 02:12
@silentnj just wanted to give you a heads up that white fixed this in https://github.com/NyxStudios/TerrariaAPI-Server/commit/651dac4982d80f0791a887447776d7d7eba1e41b (waiting on submodule update here)
