### ISSUE TITLE
UpdateManager exceptions (on mono)

### ISSUE THREAD

**Issue by Nama** [NyxStudios/TShock#836] opened 2014-09-06 09:27 UTC
I noticed, that the non-working UpdateManager spills out exceptions...
Tried on several mono 3.x versions.
Dont know how it is on Windows.

The exception appears directly after the start of the server and later, too.

![um](https://cloud.githubusercontent.com/assets/2297270/4174781/f8e4d160-35a7-11e4-8d95-ab72f1a11f1a.jpg)

**Comment by maxpowa** [comment] 2015-01-30 06:29
I can confirm it still happens with latest release, v4.2400 (da85655).

'''
 UpdateManager Exception: System.Net.WebException: Error getting response stream (Write: The authentication or decryption has failed.): SendFailure ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: Invalid certificate received from server. Error code: 0xffffffff800b010a
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.RemoteValidation (Mono.Security.Protocol.Tls.ClientContext context, AlertDescription description) [0x00000] in <filename unknown>:0
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.validateCertificates (Mono.Security.X509.X509CertificateCollection certificates) [0x00000] in <filename unknown>:0
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.ProcessAsTls1 () [0x00000] in <filename unknown>:0
  at Mono.Security.Protocol.Tls.Handshake.HandshakeMessage.Process () [0x00000] in <filename unknown>:0
  at (wrapper remoting-invoke-with-check) Mono.Security.Protocol.Tls.Handshake.HandshakeMessage:Process ()
  at Mono.Security.Protocol.Tls.ClientRecordProtocol.ProcessHandshakeMessage (Mono.Security.Protocol.Tls.TlsStream handMsg) [0x00000] in <filename unknown>:0
  at Mono.Security.Protocol.Tls.RecordProtocol.InternalReceiveRecordCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0
  at System.Net.HttpWebRequest.GetResponse () [0x00000] in <filename unknown>:0
  at TShockAPI.Utils.GetResponseNoException (System.Net.HttpWebRequest req) [0x00000] in <filename unknown>:0
'''
Fresh install, following http://tshock.co/xf/index.php?threads/installing-tshock-on-debian-wheezy.1873

**Comment by sauldrod** [comment] 2015-02-01 09:15
Same problem here, using Ubuntu 14.04, fresh install.

**Comment by Deathmax** [comment] 2015-02-01 09:21
This is likely because [Mono doesn't trust any SSL certs by default](http://www.mono-project.com/docs/faq/security/).

**Comment by nicatronTg** [comment] 2015-02-02 23:04
I wonder if we could just change the url to http, or if Github will just force a redirect to https?

**Comment by storayy** [comment] 2015-02-03 22:10
anybody find a fix to this issue? i'm running mono on ubuntu 14.04.

<code>
: UpdateManager Exception: System.Net.WebException: Error getting response stream (Write: The authentication or decryption has failed.): SendFailure ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: Invalid certificate received from server. Error code: 0xffffffff800b010a
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.RemoteValidation (Mono.Security.Protocol.Tls.ClientContext context, AlertDescription description) [0x00000] in <filename unknown>:0
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.validateCertificates (Mono.Security.X509.X509CertificateCollection certificates) [0x00000] in <filename unknown>:0
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.ProcessAsTls1 () [0x00000] in <filename unknown>:0
  at Mono.Security.Protocol.Tls.Handshake.HandshakeMessage.Process () [0x00000] in <filename unknown>:0
  at (wrapper remoting-invoke-with-check) Mono.Security.Protocol.Tls.Handshake.HandshakeMessage:Process ()
  at Mono.Security.Protocol.Tls.ClientRecordProtocol.ProcessHandshakeMessage (Mono.Security.Protocol.Tls.TlsStream handMsg) [0x00000] in <filename unknown>:0
  at Mono.Security.Protocol.Tls.RecordProtocol.InternalReceiveRecordCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0
  at System.Net.HttpWebRequest.GetResponse () [0x00000] in <filename unknown>:0
  at TShockAPI.Utils.GetResponseNoException (System.Net.HttpWebRequest req) [0x00000] in <filename unknown>:0
</code>

**Comment by cyboman33** [comment] 2015-02-04 05:29
Hi,

i use OpenSUSE 13.2 and had the same problem.

 

http://www.mono-project.com/docs/faq/security/

 

Use the mozroots.exe tool (included in Mono 1.1.10 and later) to download and install all Mozilla’s root certificates (i.e. the ones used in FireFox and other Mozilla’s softwares). It’s easier than finding a specific root but it’s also less granular to make a decision about which one(s) you install or not.


 

After that the error is gone. 

 


Gesendet: Dienstag, 03. Februar 2015 um 23:10 Uhr
Von: storayy <notifications@github.com>
An: NyxStudios/TShock <TShock@noreply.github.com>
Betreff: Re: [TShock] UpdateManager exceptions (on mono) (#836)


anybody find a fix to this issue? i'm running mono on ubuntu 14.04.


: UpdateManager Exception: System.Net.WebException: Error getting response stream (Write: The authentication or decryption has failed.): SendFailure ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: Invalid certificate received from server. Error code: 0xffffffff800b010a
at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.RemoteValidation (Mono.Security.Protocol.Tls.ClientContext context, AlertDescription description) [0x00000] in :0
at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.validateCertificates (Mono.Security.X509.X509CertificateCollection certificates) [0x00000] in :0
at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.ProcessAsTls1 () [0x00000] in :0
at Mono.Security.Protocol.Tls.Handshake.HandshakeMessage.Process () [0x00000] in :0
at (wrapper remoting-invoke-with-check) Mono.Security.Protocol.Tls.Handshake.HandshakeMessage:Process ()
at Mono.Security.Protocol.Tls.ClientRecordProtocol.ProcessHandshakeMessage (Mono.Security.Protocol.Tls.TlsStream handMsg) [0x00000] in :0
at Mono.Security.Protocol.Tls.RecordProtocol.InternalReceiveRecordCallback (IAsyncResult asyncResult) [0x00000] in :0
--- End of inner exception stack trace ---
at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (IAsyncResult asyncResult) [0x00000] in :0
--- End of inner exception stack trace ---
at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in :0
at System.Net.HttpWebRequest.GetResponse () [0x00000] in :0
at TShockAPI.Utils.GetResponseNoException (System.Net.HttpWebRequest req) [0x00000] in :0

**Comment by nicatronTg** [comment] 2015-02-04 05:32
@Deathmax @Olink I wonder if it would be smart to have TShock offer to install certs using Mozroots.exe as a workaround? I'll write the code for it if that seems like a good move.

**Comment by Nama** [comment] 2015-02-08 22:32
I executed `mozroots --ask-remove --import` and now I am getting this error on start
```
UpdateManager Exception: System.Net.WebException: The request timed out
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0
  at System.Net.HttpWebRequest.GetResponse () [0x00000] in <filename unknown>:0
  at TShockAPI.Utils.GetResponseNoException (System.Net.HttpWebRequest req) [0x00000] in <filename unknown>:0
```
I guess this is the same error Windows servers get also, cause it isn't even working?

**Comment by nicatronTg** [comment] 2015-02-09 00:09
This error so far doesn't affect Windows. Nobody has confirmed it on
Windows. Are you using mozroots correctly?

**Comment by Olink** [comment] 2015-02-15 05:46
Honestly, we shouldnt even have an update manager and would like to slap whoever brought it back.  Secondly, if we are going to keep it, we shouldnt be using a file in github repo to determine what the latest is, we should be using our server.

**Comment by nicatronTg** [comment] 2015-02-15 07:46
That's silly @Olink. Every program has auto update or at least a notification system of sorts. With that being said, Github does have the benefit of being a global CDN that's reliable uptime wise (not that we've had problems lately with that). Mozroots would be the easiest way to implement a workaround but not great long term.

**Comment by Olink** [comment] 2015-02-17 00:11
Its silly to provide an "update checker" for a piece of software that has no auto update, and can easily be abused by a developer.  If someone forgets to update it, no one would notice.  If someone updates it without making a new release, no one would notice.  Given that the update checker has done nothing but cause problems, it doesn't make sense from to keep it.  

This seems to be going without being said, but as the ONLY developer, I don't think your opinion is even remotely relevant.  If you want to dictate where development time goes, you should become a developer and not a paper pusher.

**Comment by sfrenchy** [comment] 2015-02-17 00:13
"but as the ONLY developer, I don't think your opinion is even remotely relevant. If you want to dictate where development time goes, you should become a developer and not a paper pusher."

oooooooooooooooooooooooo snap

**Comment by Olink** [comment] 2015-02-17 00:13
Also, forcing end users to install thirdparty software for a update checking is the same thing as asking them to just install an rss feed checker to check for new threads in the announcement section.  Its over the top and pretty ugly.  Obviously that is the current work around, but it shouldnt even be a thing.

**Comment by nicatronTg** [comment] 2015-02-17 00:15
Mozroots comes with mono, afaik, and also, as long as it says owner next to my name, my opinion is still relevant ;)

**Comment by Olink** [comment] 2015-02-17 00:17
Not really.  Because any opinion you have will never result in actuality.  You can be owner all day, but the moment I fork it to my account and push updates to the forums, your hat is useless.

**Comment by nicatronTg** [comment] 2015-02-17 00:17
@Olink smartass, I offered to implement it if that was the collective decision

**Comment by maxpowa** [comment] 2015-02-17 00:18
Honestly though how useful is an update checker on a server software that you start once and leave unattended. If the server crashes, I'd check my versions and update if there's one available. Update checkers and those sort of things are things for helping less technically inclined end users anyways.

**Comment by Olink** [comment] 2015-02-17 00:18
Implement it?  Implement installing third party software?  I thought I made it clear that any solution should be reflected by changing the implementation, not stacking more cruft and garbage on top.

**Comment by nicatronTg** [comment] 2015-02-17 00:19
@Olink again mozroots.exe is included with mono; as simple as executing it on every mono server

**Comment by nicatronTg** [comment] 2015-02-17 00:20
@maxpowa you shouldn't be running a server without administration

**Comment by Olink** [comment] 2015-02-17 00:20
@nicatrontg smartass, youve offered to implement a lot of shit over the years, and had about a 1% return value on those claims.  I end up picking up the other 99%.  But please, tell me how commited you are to commiting to a project you havnt in over a year.

Whether it comes with mono or not, running an application for an end user is not a solution, and not something I want TShock to have to do.  We don't install mono for users on non windows machines for them, do we?

**Comment by maxpowa** [comment] 2015-02-17 00:21
@nicatronTg what does administration have anything to do with the update checker? You shouldn't be running a server if you're unable to check for updates yourself. There's no point in server software doing it for me.

**Comment by Olink** [comment] 2015-02-17 00:21
The most I feel comfortable doing is putting in the readme and wiki that they need the moz certs to run update checker, and leave it at that unless someone has a software solution.

**Comment by maxpowa** [comment] 2015-02-17 00:21
Could you suppress the error if the user opts to not do the mozroots?

**Comment by Olink** [comment] 2015-02-17 00:22
It should only print once if it fails, and if not thats a quick solution to add.

**Comment by nicatronTg** [comment] 2015-02-17 00:22
@Olink then do that and close the issue, don't leave it open for, say, months without commenting even after the fix doesn't work

@maxpowa that's also possible

**Comment by maxpowa** [comment] 2015-02-17 00:23
@Olink currently it prints the error once every time the server is started.

**Comment by Olink** [comment] 2015-02-17 00:23
Yes, thats the intended behavior of failed web applications.  If it fails once, retry silently.

**Comment by maxpowa** [comment] 2015-02-17 00:25
I'm just saying suppress the stacktrace or something, maybe make it so it checks for ```WebException``` and just says ```Update manager failed to check for updates, consider running mozroots.exe --ask-remove --import```

**Comment by nicatronTg** [comment] 2015-02-17 00:26
@maxpowa @Olink is correct -- the behavior is intended to notify of failure at least once. Again, another possible solution.

**Comment by maxpowa** [comment] 2015-02-17 00:26
Stacktraces in production are never a good idea.

**Comment by Olink** [comment] 2015-02-17 00:27
@nicatronTg It was left open for months because at the time no one replied whether the change to using a different hhtp method fixed anything.  I only just saw it was open when you linked to it again.  As we have said for years, the github issues section is not the correct place to post actual issues.  As we have said for months, TShock is a maintenance only project.  Apparently our forum mods are useless at informing the developers of any major bugs reported, and since you and I both know that neither one of us have the spare time to be hawks on a project that neither one of us want to continue working on.  We both let this issue stay open for months, dont accuse me of leaving it open on purpose.  As this issue is for an OS that we don't support, it really comes down to the mono community posting a fix in the mono section on the forums.

**Comment by nicatronTg** [comment] 2015-02-17 00:32
@Olink (see hipchat)

Outside collabs, don't mind the minor confrontation above.

**Comment by nicatronTg** [comment] 2015-02-17 00:40
Alright, in order to solve this issue, I'm getting a system up that will support updating the version file from a remote server.

**Closed** 2015-02-21 22:29 UTC
