### ISSUE TITLE
coin portal gave zero coins

### ISSUE THREAD

**Issue by moozaad** [NyxStudios/TShock#974] opened 2015-07-08 16:46 UTC
Wiki suggests it is 5-15 gold coins but this one created the portal and then nothing dropped out.

WIn 7, Bamboo build 428 on medium normal world.

Been unable to repro due to rarity (and can't spawn pots).
What I did was created new world and smashed a bunch of pots. Saw the portal but no coins. Portal showed the proper animation and length.

ref: http://terraria.gamepedia.com/Pot#Coin_Portals

**Comment by Nixola** [comment] 2015-07-08 17:00
Happened to me as well, in a newly created small world, not expert.

**Comment by guitarguy1133** [comment] 2015-07-08 17:05
Also happens to me.

**Comment by Ijwu** [comment] 2015-07-08 17:19
Try removing TShock from ServerPlugins and attempt to repeat. I'd like to know if this continues even without TShock being loaded.

**Comment by moozaad** [comment] 2015-07-08 17:31
Still does it without TShockAPI.dll in plugins.

**Comment by AndrioCelos** [comment] 2015-07-15 14:56
It would be helpful to modify the API server to always produce a coin portal.

**Comment by moozaad** [comment] 2015-07-19 22:40
I saw one work today in hard mode. I think the server is on 489

**Comment by Ijwu** [comment] 2015-07-19 23:12
Closing for the moment as there have been no repeat reports in 11 days and @moozaad has reported the problem is, so far, gone.

**Closed by Ijwu** 2015-07-19 23:12 UTC
Labels: Confirmed Issue

**Comment by guitarguy1133** [comment] 2015-07-20 21:25
I'll try to record it the next time it happens...

**Comment by guitarguy1133** [comment] 2015-07-20 21:26
I'll try to record it the next time it happens...  if it happens

**Comment by WhiteXZ** [comment] 2015-07-21 02:50
I had working portals on build 497
