### ISSUE TITLE
When you teleport a player when they are dead, their body parts are all over the place

### ISSUE THREAD

**Issue by ZakFahey** [NyxStudios/TShock#1331] opened 2016-12-01 00:40 UTC
The position of all the parts of a player doesn't seem to reset until after you die, so when a player is teleported with /tp, /warp, etc. they appear to be dismembered heads, feet, and so on.

My suggestion would be to have these commands not warp you if you are dead but instead queue you to be teleported as soon as your respawn.

**Comment by tlworks** [comment] 2016-12-01 13:17
This way or may not be relevant to the issue described above, but basically if you warp or teleport somewhere and the monsters are either dead or non existent. They end up just being on your screen with 1/X HP left. You can kill them to get them off your screen but could somewhat be annoying since they still deal damage.

**Comment by ProfessorXZ** [comment] 2016-12-10 21:37
Please confirm this is not caused by the modified version of your server.

**Comment by ZakFahey** [comment] 2016-12-10 21:48
I just tested it on the most recent TShock pre-release, and it doesn't happen. On my server you immediately spawn if you're dead and you get teleported, but on the pre-release you just stay dead until you spawn normally.

**Comment by ProfessorXZ** [comment] 2016-12-10 23:04
Then this isn't really an issue, right?

**Comment by ProfessorXZ** [comment] 2016-12-21 18:38
As per @ZakFahey this does not happen in the pre-release and thus serves no purpose at the moment really. Keep in mind that modified builds are not and never have been supported by TShock, so make sure to confirm these issue in the actual (pre)release. 

I'm going to close the issue for now, feel free to re-open if it re-occurs.

**Closed by ProfessorXZ** 2016-12-21 18:38 UTC
