### ISSUE TITLE
Several plugins does not load on lastest unstable build (1596)

### ISSUE THREAD

**Issue by tanpro260196** [NyxStudios/TShock#1439] opened 2017-05-03 07:57 UTC
For example, Ancientgod's Chestroom plugin return this error:

`[Server API] Error Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "Chestroom" has thrown an exception during initialization. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at ChestroomPlugin.ChestroomPlugin.ReadConfig()
   at ChestroomPlugin.ChestroomPlugin.Initialize()
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game)
   at TerrariaApi.Server.HookManager.InitialiseAPI()`

The same goes for Region Trigger (Could not load Newtonsoft.Json), Seconomy (Could not load tshockapi.dll) and Enerdy's Discord Bridge and some other plugins.

**Comment by WhiteXZ** [comment] 2017-05-03 08:03
Update those plugins to use Newtonsoft.Json version 10

**Comment by tanpro260196** [comment] 2017-05-03 08:05
where can I get that? The file that goes with tshock is 9.0.1.

**Comment by tanpro260196** [comment] 2017-05-03 08:15
Ok, I tried with the new file from here: https://www.nuget.org/packages/newtonsoft.json/
Nothing change, same error.

**Comment by tanpro260196** [comment] 2017-05-03 08:32
Thanks, that works for some, but then there is this:

Seconomy
'[Server API] Error Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Failed to load assembly "Wolfje.Plugins.Jist.dll". ---> System.InvalidOperationException: Could not create an instance of plugin class "Wolfje.Plugins.Jist.JistPlugin". ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'TShockAPI, Version=4.3.21.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at Wolfje.Plugins.Jist.JistPlugin..ctor(Main game)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game)
   at TerrariaApi.Server.HookManager.InitialiseAPI()'


Region Trigger:

`[Server API] Warning Plugin "RegionTrigger" has had an unhandled exception thrown by one of its GameInitialize handlers:
System.IO.FileNotFoundException: Could not load file or assembly 'MySql.Data, Version=6.9.9.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d' or one of its dependencies. The system cannot find the file specified.
File name: 'MySql.Data, Version=6.9.9.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d'
   at RegionTrigger.RtRegionManager..ctor(IDbConnection db)
   at RegionTrigger.RegionTrigger.OnInitialize(EventArgs args)
   at TerrariaApi.Server.HandlerCollection`1.Invoke(ArgsType args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog]'

**Comment by WhiteXZ** [comment] 2017-05-03 08:35
Do the same as before, but with TShock.dll version 4.321.0 and MySql.Data.dll version 6.9.9.0

**Comment by tanpro260196** [comment] 2017-05-03 08:46
oh well, guess I gonna stay with the old build for a while then, but why does this happened anyway?
tshock does not normaly require exact file version like this...

**Comment by Enerdy** [comment] 2017-05-03 10:09
This is a result of the recently added recursive asssembly resolver.
It will now search subdirectories along with the base ServerPlugins folder, but in order for it to load the right dependencies for each plugin, it was changed to use an assembly's full name, which includes the file version. We are aware that this effectively breaks -ignoreversion functionality and discussion is open for whether we should look into a workaround.

**Comment by mistzzt** [comment] 2017-05-03 11:31
@tanpro260196 
The problem of RegionTrigger has been fixed on the latest release:
https://github.com/mistzzt/RegionTrigger/releases

**Comment by Ijwu** [comment] 2017-05-03 15:10
Is this still an issue? @tanpro260196

**Comment by hakusaro** [comment] 2017-05-03 15:23
I'm gonna go ahead and say this is definitely a problem. Um, where do you plan to source developers to update all plugins to use recent assembly versions, @Ijwu?

Seems to me like -ignoreversion should just not try to resolve every assembly exactly.

**Comment by Ijwu** [comment] 2017-05-03 15:50
@hakusaro It may be that I've misunderstood the issue. Perhaps some more intelligence put into the recursive loading may be necessary. I'd hate to have to build and resolve a dependency tree, but that may be required to optimally load all plugins without issue.

**Comment by hakusaro** [comment] 2017-05-03 15:52
The problem is that people are forced to find old versions of _TShock_ even for the most basic plugins. It's like we've hard locked everything down so much that you can't even upgrade your server without including the original TShockAPI.dll something was built with.

**Comment by tanpro260196** [comment] 2017-05-03 17:43
Don't know why but recompile the plugin with the file from tshock_release.zip just does not works.
It still require exact file version, where can I change that in Visual Studio 2017?

**Comment by hakusaro** [comment] 2017-05-03 23:08
At least two other people have reported this "issue" in the last 24 hours.

**Comment by ProfessorXZ** [comment] 2017-06-22 19:42
Can anyone confirm this is still an issue? @tanpro260196

**Comment by tanpro260196** [comment] 2017-06-22 20:10
No, it's fixed now. @ProfessorXZ

**Closed** 2017-06-22 20:11 UTC
