### ISSUE TITLE
Celestial Sigil non-functional

### ISSUE THREAD

**Issue by BStorm888** [NyxStudios/TShock#1181] opened 2016-05-09 05:21 UTC
When attempting to use the item, the item is consumed but nothing happens, even though the world meets all the requirements for using it. Works fine on single player and Steam multiplayer but not when on the TShock server.

**Comment by WhiteXZ** [comment] 2016-05-09 05:34
Duplicate of https://github.com/NyxStudios/TShock/issues/1065, solved in https://github.com/NyxStudios/TShock/pull/1163. This patch has not been released yet, but you its effects are present in the latest [Bamboo builds](https://bamboo.tshock.co/browse/TERRA-TSHOCK).

**Closed by WhiteXZ** 2016-05-09 05:34 UTC
