### ISSUE TITLE
TShock Mintaka (Unstable build 1378) - Messing up inventories!

### ISSUE THREAD

**Issue by MineBartekSA** [NyxStudios/TShock#1337] opened 2016-12-10 14:24 UTC
Hello.
I'm trying to make a home terraria server with TShock Mintaka (Unstable build 1378).
Evrythings fine SSC works but SSC messup evry tsCharacter in my database! (I use my private MySQL Database and i have bacup of my DB).

Here is some screanshots on Terraria 1.3.4.3 (TShock unsable build 1368) : 
![1 3 4 3 - inv](https://cloud.githubusercontent.com/assets/19757593/21073916/3b03f1f0-beec-11e6-8a14-daf58cd8ca48.JPG)

![1 3 4 3 - accesoris](https://cloud.githubusercontent.com/assets/19757593/21073917/43289e1c-beec-11e6-8c49-1a2fd5ef2b45.JPG)

![1 3 4 3 - accesoris - 2](https://cloud.githubusercontent.com/assets/19757593/21073918/4606cf00-beec-11e6-9572-111ecb34ece3.JPG)

And here is some screanshots on Terraria 1.3.4.4 (TShock Mintaka (Unstable build 1378)) : 
![1 3 4 4 - inv](https://cloud.githubusercontent.com/assets/19757593/21073921/678ae30a-beec-11e6-9678-2aa0ba0801af.JPG)

![1 3 4 4 - accesoris](https://cloud.githubusercontent.com/assets/19757593/21073922/6ab2da9c-beec-11e6-98e1-c7b5976bd1f8.JPG)

![1 3 4 4 - accesoris - 2](https://cloud.githubusercontent.com/assets/19757593/21073923/6d94282e-beec-11e6-840a-45a6fb28400f.JPG)

Fortunately i buckup my Database and world before running Tshock Mintaka.

And i notice that it only mess up with my Accesories.

**Comment by tlworks** [comment] 2016-12-10 14:31
You'll have to live with that, all your 'lost' items can be found in the Forge (Bank3). Happens to everyone switching towards the newer version.

**Comment by MineBartekSA** [comment] 2016-12-10 15:27
ok thanks

**Comment by ProfessorXZ** [comment] 2016-12-10 15:32
Reopening this as it is an actual issue.

**Comment by ProfessorXZ** [comment] 2016-12-10 16:25
Do you have any reproduction steps?

**Comment by MineBartekSA** [comment] 2016-12-10 16:35
What do you mean?
And i have backup evrything so i can just run old version of server and Terraria and see what i have.
But new version overwrite my database so i must import data to see what i lose

**Comment by Kojirremer** [comment] 2016-12-10 16:41
If this info is useful, the latest unstable, non-Mintaka 1.3.4.3 build from late november caused this same issue to me.
Haven't tried Mintaka yet due to extreme plugin shortage, but maybe the inventory was disordered when he tried the non-Mintaka 1.3.4.3, and actually got corrected when switching to Mintaka?

**Comment by MineBartekSA** [comment] 2016-12-10 17:26
I don't use the lastet non-Mintaka 1.3.4.3 build. I use build number 1368 from 21 November.
And i switch from lastet TShock version (4.3.20) and evrything was fine!
So maby this build from 21 November broke my database or lastat build of Mintaka broke it.

**Comment by whatsup1827** [comment] 2016-12-10 18:26
This is kinda unrelated but this is topic number 1337 lol

**Comment by ProfessorXZ** [comment] 2016-12-10 19:38
@Kojirremer Yes I thought so. This is not an issue with Mintaka. Could you describe what happens and how? Do you first log in then logout and log back in? Is the user superadmin? Describe the whole process if you can.

**Comment by MineBartekSA** [comment] 2016-12-10 20:07
Em...
Sometime ago i recreate a tshock server that are using my own MySQL DB on Unstable build of TShock for 1.3.4.3 (Build number 1368) and i don't play that much so when the Mintaka version was avaible to download i just update this server and i log in but there no items form SSC so i relog and still no items. I ask on TShock slack waht is going on and i someone told me that in thsi version SSC don't work. In next day (today) i donwload a lastat version of TShock Mintaka and upated the server and SSC work but i noticed that my character change. I don't now what but i start testing my plugin (that i update for myself yesterday) and it work but not all function (i edit something in my code i must check if it is working now) and then i try to use my hook but it's gone! Now i now something is wrong so i donwload form internet (i have bought Terraria but i don't have this version on computer) 1.3.4.3 version of terraria to check my inv in this terraria version. And i re create this server with TShock for 1.3.4.3 (Build number 1368) again and join this server and there no changes in my inv so i restore my backup of my DB and i join the server. Then i realize that some my accesories are gone on Mintaka version! So i take a screanshots of my inv and start mintaka and again taka some screanshots of my inv on mintaka and i wrote this issue.

I think that you want. I don't use my superadmin account. I only use it when SSC don't work with mintaka to try something with SSC. If you want i can send my database after and now. I hope this will help.

**Comment by ProfessorXZ** [comment] 2016-12-11 07:54
@MineBartekSA please please please tell me how to reproduce this please please please

**Comment by MineBartekSA** [comment] 2016-12-11 14:30
Em...
I don't now what i should tell you. How to reproduce what?

Sorry for that late awnser but i don't have time.

**Comment by Enerdy** [comment] 2016-12-11 15:34
@MineBartekSA He meant the steps you have to follow in order to have this happen, because it doesn't seem to be happening to everyone. If you cannot reproduce it anymore then we'll have to assume it has been fixed and this should be closed.

**Comment by MineBartekSA** [comment] 2016-12-11 17:11
Then i : 
 - I Download Pre-Release TShock Mintaka 4.3.21 for Terraria 1.3.4.4 (APIv1.26, OTAPI v2.0.0.9) from GitHub
 - I backup my worlds and i backup my Database
 - I open the zip file and copy it to the folder where i had a server on TShock (Unstable build number 1368)
 - I check the config and start server and game
 - I update my plugin and restart server
 - I joined server and SSC don't work so i don't have my items
 - Next day (yesterday) i download the TShock Mintaka unstable build number 1378 (tshock_release.zip file)
 - I open the zip file and copy it to the folder
 - I start the server and game and joined server
 - SSC work but my accesories are broken

I did this and i can start 1.3.4.3 game and server with that config and import DB back up and it's evrything fine but if i switch to Mintaka then this happends.

**Comment by Enerdy** [comment] 2016-12-14 15:08
This was fixed in #1342, which is live now in our unstable builds repository. Will re-open if the issue pops up again.

**Closed by Enerdy** 2016-12-14 15:08 UTC

**Comment by MineBartekSA** [comment] 2016-12-26 22:09
Good day!
This happend again on TerraVerse!
But it seams that this onlu happends me on my very good nick MineBartekSA!
So if someone read this you can close this or fix this i don't care!

**Comment by Marcus101RR** [comment] 2016-12-26 22:20
@MineBartekSA You didn't specify which version you are using.

**Comment by ProfessorXZ** [comment] 2016-12-26 22:20
I'm confused honestly. This issue is already closed, do you want it re-opened? If that is the case, this was already fixed and tested. I don't know what TerraVerse is but the issue you're experiencing may be caused by the usage of outdated plugins, modifying TShock's source etc. All in all, this is already fixed.

**Comment by MineBartekSA** [comment] 2016-12-26 22:27
no i don't idk hat happend but it's only my so it's not a big deal

**Comment by Marcus101RR** [comment] 2016-12-26 22:29
@MineBartekSA What build are you using? You still didn't specify it, are you using a pre-release, a build from the travis location?

**Comment by MineBartekSA** [comment] 2016-12-26 22:32
Mintaka pre 2 Terraverse use

**Comment by Kojirremer** [comment] 2016-12-26 23:21
I used the latest build from 12-23 and got the messed inventories as well, but since no one else is having the same issue I'm assuming it's a plugin thing.
Mind posting which plugins you were using? Maybe a chest-related one? Just want to know which plugins we're using match so I can isolate the problem.

**Comment by DogooFalchion** [comment] 2016-12-28 00:20
If you every launched the game with an older build your character data was permanently broken.  You would need to be able to reproduce this with a clean database on the latest version with steps to 100% reproduce otherwise we can't really fix it.
