### ISSUE TITLE
Flower Boots not making flowers

### ISSUE THREAD

**Issue by ItWasUncalledFor** [NyxStudios/TShock#1021] opened 2015-07-16 21:10 UTC
When using flower boots on multiplayer, boots will not generate flowers while walking on grass

**Comment by P2Mc28** [comment] 2015-07-17 00:05
It's permissions related I bet; they work when I log in as Super Admin.

**Comment by Puremin0rez** [comment] 2015-07-19 08:51
I can confirm this, flowers are not created with flower boots but they are for super admin. Not sure why?

**Comment by WhiteXZ** [comment] 2015-07-19 13:13
Likely due to superadmin having the 
```C# 
tshock.ignore.sendtilesquare
```
permission

**Comment by DaBomberNTG** [comment] 2015-07-28 02:41
Tested, as long as the group your in has "tshock.ignore.sendtilesquare" you can create flowers. This can be closed.

**Comment by nicatronTg** [comment] 2016-10-11 01:37
Do we want to do anything to try and monkey patch this @WhiteXZ?

**Comment by nicatronTg** [comment] 2016-10-11 01:56
_I am assigned to this issue for monitoring/oversight but am not actively working this issue._

**Closed** 2016-10-16 23:18 UTC
Labels: Confirmed Issue, Pull Request Wanted
