### ISSUE TITLE
Bosses spawn in same spot?

### ISSUE THREAD

**Issue by morphboy001** [NyxStudios/TShock#1014] opened 2015-07-16 07:05 UTC
Is it normal for when i spawn bosses and mobs they spawn in the same spot?

**Comment by WhiteXZ** [comment] 2015-07-16 07:06
Likely an issue with how we determine spawn positions

**Comment by morphboy001** [comment] 2015-07-16 10:17
So, is there someway i can fix it or is it a issue?

**Comment by WhiteXZ** [comment] 2015-07-16 14:40
It's an issue, will look into it

**Comment by gheta** [comment] 2015-07-24 20:46
It wasn't always like this right? I remember before they used to summon in many locations for us at once until I believe the 1.3 update.

**Comment by Patrikkk** [comment] 2015-07-24 21:29
What do you mean by this exactly?
/spawnmob command?
Or /spawnboss?
I spawned some mobs previously, and they all spawned different locations. Same with bosses.

**Comment by gheta** [comment] 2015-07-27 13:55
@Patrikkk Most of the time when I've recently spawned bosses since Terraria 1.3, Say "/sb destroyer 12," it summons all Destroyers on top of each other. You look like you are fighting 1 Destroyer, but really it's 12 heads combined into one. Last night I summoned 20 Skeletron Primes and they didn't summon on top of each other so idk if the current build fixed the issue because I didn't go far into testing. But the Skeletron Primes did all get almost on top of each other after a few minutes and follow the exact same patterns. Mobs never summoned on top of each other for me, just bosses.

**Comment by Patrikkk** [comment] 2015-07-27 19:56
Hey,  I spawned some bosses a few times to try reproduce the issue. (latest release, 4.3.7)
And they properly spawned scattered around. 
Can we close this issue till no new reports about it? (since gheta said he couldn't reproduce after switching to newer build either.)

**Comment by WhiteXZ** [comment] 2015-07-28 03:31
This was probably fixed in https://github.com/NyxStudios/TShock/commit/1ab66128ab4969bd211e00133f8a0503b52564a2 - the random is properly random now. Spawned bosses of the same type will eventually overlap each other due to having the same AI

**Closed by WhiteXZ** 2015-07-28 03:31 UTC
Labels: Needs Investigation
