### ISSUE TITLE
System.OverflowException also Crash Reporter didn't create crash dump...

### ISSUE THREAD

**Issue by Hiarni** [NyxStudios/TShock#1089] opened 2015-08-17 18:38 UTC
TShock: ERROR: System.OverflowException: Arithmetic operation resulted in an overflow.
   at TerrariaApi.Server.HookManager.InvokeNetGetData(Byte& msgId, MessageBuffer buffer, Int32& index, Int32& length)
   at Terraria.MessageBuffer.GetData(Int32 start, Int32 length)
   at Terraria.NetMessage.CheckBytes(Int32 bufferIndex)
   at Terraria.Netplay.ServerLoop(Object threadContext)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

_________________

===================================================================================
[08.17.15 19:22:07] [Server API] Error: An unhandled exception has occured in TSAPI, and a crash report will be generated
[08.17.15 19:22:07] [Server API] Error: Generating a crash report, please wait...
[08.17.15 19:22:09] [Server API] Error: Could not generate a crash report.
[08.17.15 19:22:09] [Server API] Error: Please upload the crash file and report it at http://tshock.co/
[08.17.15 19:22:09] [Server API] Error: The process will terminate.

**Comment by Hiarni** [comment] 2015-08-17 21:16
well... i setup an automated standalone dump generation process aside of tshock's one (since tshock's didn't worked for me several times with 4.3.9's reporter).

i will post dump file and also debug logs of tshock/terrariaserver.exe at the next crash procedure (around 24h)

**Comment by TeeriaLLC** [comment] 2015-08-17 22:14
Same happened to me, as shown in the images below the server crashed and did not create a log.

https://i.gyazo.com/459aed346034b61448b1e7d7b2c74364.png
https://i.gyazo.com/742bda957ac930a69b17a607c9f14cb4.png

**Comment by TeeriaLLC** [comment] 2015-08-17 22:19
Was during a celestial event, so that could be the cause.

**Comment by TeeriaLLC** [comment] 2015-08-17 22:49
@tylerjwatson

**Comment by tylerjwatson** [comment] 2015-08-18 03:42
The crash reporter isn't going to be able to create a crash dump if it can't (eg. not enough memory, common on large worlds)

**Comment by Hiarni** [comment] 2015-08-18 17:12
ok there we go it has finally crashed again and the dump file was generated with my external tools automated including pid

https://www.dropbox.com/s/wqt1pdpgtxdjj5y/TerrariaServer__PID__3080__Date__08_18_2015__Time_04_27_20PM__594__Log.txt?dl=0

https://www.dropbox.com/s/lthwf6yy994120o/TerrariaServer__PID__3080__Date__08_18_2015__Time_07_02_00PM__937__Second_Chance_Exception_E0434352.dmp?dl=0

**Comment by Hiarni** [comment] 2015-08-18 17:42
well... it seems it was another crash reason at this point...
i'll upload the system.overflowexception crash dump soon!

**Comment by tylerjwatson** [comment] 2015-08-19 08:33
This crash dump contains literally hundreds of exceptions from TSReward.  I am going to start closing issues that people create where they haven't removed all plugins apart from TShock before submitting.  This is a serious waste of time and my bandwidth.

![image](https://cloud.githubusercontent.com/assets/5001408/9351959/ce742646-46a0-11e5-8a79-b93b97d32202.png)

**Closed by tylerjwatson** 2015-08-19 08:33 UTC

**Comment by TeeriaLLC** [comment] 2015-08-19 10:15
Nobody in the ever will run a clean TShock at all times.
