### ISSUE TITLE
[SSC] HP randomly resets to 100

### ISSUE THREAD

**Issue by Stealownz** [NyxStudios/TShock#1066] opened 2015-07-31 18:35 UTC
After logging in, a player's HP randomly resets to 100.
Could not reproduce but it's still happening.

[Edit] To clarify, player was already a registered user and has used life crystals in server with SSC on. Player then lost their original MaxHP upon /login

**Comment by Kromara** [comment] 2015-07-31 18:53
I've had this same thing happen for players on my server. Players who
experience large amounts of lag or high ping seem to be common targets of
this. One player from Lebanon says that he logs on to the server and takes
a few points of fall damage, then is frozen as normal, but afterwards he
logs in and his HP is set to his Single player amount.

**Comment by Stealownz** [comment] 2015-07-31 19:54
I've had a player report that he died while logging in as well. Might be a cause.

**Comment by Kromara** [comment] 2015-07-31 22:18
Taking damage when joining the server could possibly be the cause.

**Comment by Angelyss** [comment] 2016-04-02 11:23
Seems like this issue is no longer persistent in recent builds. There have been no reports of this happening on our server in months.

**Comment by WhiteXZ** [comment] 2016-04-03 00:40
Thank you @Angelyss. I will close this for now. If future instances of this bug show up, feel free to re-open this issue.

**Closed by WhiteXZ** 2016-04-03 00:40 UTC
