### ISSUE TITLE
Bugged textures of weapons Tshock 1.3.0.5

### ISSUE THREAD

**Issue by HooTi** [NyxStudios/TShock#1031] opened 2015-07-18 15:07 UTC
Me and my friends find out that when she was shooting meteor staff on my screen she was holding copper pickaxe and shooting meteors, same with alot of weapons (bugged stardust dragon) etc. (it fixes when u will have same weapons that ur friend is using)

**Comment by Patrikkk** [comment] 2015-07-18 16:12
Are you able to re-produce the problem?  If so, some screenshots or video would be great :)

**Comment by HooTi** [comment] 2015-07-18 16:33
![capture 2015-07-18 18_31_47](https://cloud.githubusercontent.com/assets/13394804/8762510/74eb88e6-2d7b-11e5-93ec-63bddfaa1ec0.png)
This happens with every weapon that shot projectiles i see projectiles but i cant see weapon

**Comment by Patrikkk** [comment] 2015-07-24 18:55
Thanks for the screenshot :) (Sorry for the late reply)
Does the issue still occur in latest verison? 1.3.0.7 ?  (TShock,  4.3.7 ?)

**Comment by Patrikkk** [comment] 2015-07-27 20:59
Yeahh I think this issue is no moar.

**Comment by Kromara** [comment] 2015-07-28 04:13
I saw this on build #510, I believe. I'll attempt to recreate it tomorrow
after work

**Comment by kjkillercom** [comment] 2015-08-26 22:09
The issue is still happening on build 534. When I was using the Tsunami bow, my admin was telling me it looked like I was shooting arrows while eating a carrot. lol

**Comment by ImoutoAmmy** [comment] 2015-11-05 03:44
I have ran into this issue, and I am running v 4.3.11.0. Two of the other players on my server found this issue, and both of them were seeing my character hold a carrot when using water bolt. I asked them to print screen it for me. I don't know if there is anything logged I can provide, but I would be happy to look and provide that as well.

I'm going to attach the screen shots to this post.

![waterbolt](https://cloud.githubusercontent.com/assets/15664411/10959358/70e8a43e-832c-11e5-96f1-7df67d662a1d.png)
![waterbolt2](https://cloud.githubusercontent.com/assets/15664411/10959359/70e9f7ee-832c-11e5-9c79-d3767b7ca25b.png)

**Comment by Gummin** [comment] 2016-03-03 20:04
This bug has me and my friends saying stuff like "damn dude! that copper axe does loads of damage! nice man!".
It just happens sometimes, I've found no reliable way to recreate it.

**Comment by WhiteXZ** [comment] 2016-03-03 23:06
>**Gummin said**
This bug has me and my friends saying stuff like "damn dude! that copper axe does loads of damage! >nice man!".
It just happens sometimes, I've found no reliable way to recreate it.

Neither have we :(

**Comment by ProfessorXZ** [comment] 2016-08-11 19:44
I haven't seen this happen for some time now, and considering this was 1.3.0.5, wouldn't there be a possibility this was fixed? Feel free to correct me if I'm wrong, though.

**Comment by nicatronTg** [comment] 2016-08-28 14:25
Closing this issue because as @ProfessorXZ said, it's a dupe of #1008.

**Closed by nicatronTg** 2016-08-28 14:25 UTC
Labels: Confirmed Issue, Unable To Reproduce
