### ISSUE TITLE
Strange DCU limitation

### ISSUE THREAD

**Issue by Chais** [NyxStudios/TShock#1018] opened 2015-07-16 12:35 UTC
I found I'm unable to mine the outer layer of the dungeon with the DCU. I was holding a laser drill and using it manually I could mine the dungeon.
![capture 2015-07-16 14_27_29](https://cloud.githubusercontent.com/assets/1783098/8722708/9a30e44e-2bc7-11e5-9f0f-fa0e46848a7b.png)
The hole in the roof was made with the laser drill, the other blocks remaining I'm unable to remove using the DCU. The server console didn't contain any hints.

**Comment by Enerdy** [comment] 2015-07-16 12:39
Can you reproduce this in vanilla? Try loading the world with the stock server and attempt to reproduce this.

**Comment by Chais** [comment] 2015-07-16 12:41
I'm on Linux only. Means I can't use the stock server. It crashes immedeately after start. No matter if I use wine or mono.

**Comment by WhiteXZ** [comment] 2015-07-16 12:42
Reopen once it's been tested on vanilla and in singleplayer.

**Comment by Chais** [comment] 2015-07-16 12:53
In singleplayer it works flawlessly.
![capture 2015-07-16 14_51_42](https://cloud.githubusercontent.com/assets/1783098/8722982/6206bdb6-2bca-11e5-876b-022aa6721ed9.png)

**Comment by nicatronTg** [comment] 2015-07-16 12:57
Logged in as a superadmin or a normal user?

**Comment by Chais** [comment] 2015-07-16 12:59
On TShock as superadmin. In singleplayer, well ;)

**Comment by WhiteXZ** [comment] 2015-07-17 05:27
Problem on TShock's end, will be fixed sometime

**Comment by HairyMilkshakes** [comment] 2015-07-24 18:48
Just ran into this problem again. It seems to be tied to the way background objects are formed sometimes. I notice that the unbreakable blocks line the edge of no particular background type. But as soon as I interact with one tile from that group, I can break the whole section again.

**Comment by Techjar** [comment] 2015-07-27 02:27
I'd also like to note that random large sections of the world cannot be broken either. I have discovered that the DCU works correctly if you have a pickaxe/axe tool selected while using it.

**Comment by trigger-death** [comment] 2015-08-11 16:43
This also seems to be a big problem with trees. Hopefully it gets fixed soon. I was hoping to use TShock for my Mine the World events.

**Comment by xodial** [comment] 2015-08-13 19:57
I've had good luck using the DCU while holding the picsaw.  If I have a weapon or anything else out, I have a lot of issues.

**Closed** 2015-09-06 09:01 UTC
Labels: Confirmed Issue
