### ISSUE TITLE
[Chat Above Heads] Tags only works for client, not for receivers...

### ISSUE THREAD

**Issue by Marcus101RR** [NyxStudios/TShock#1157] opened 2016-01-28 05:33 UTC
As you can see,

The person typing on their own screen can see the text color fine, however, those who are receiving the text see the full code...

Using the Chat Above Heads feature. Hopefully this can be changed in the future?

![image](https://cloud.githubusercontent.com/assets/8344293/12635947/8ec25ae2-c556-11e5-9754-cf3451f8487e.png)

**Comment by Enerdy** [comment] 2016-01-28 09:27
Don't use ChatAboveHeads.

**Comment by WhiteXZ** [comment] 2016-01-28 10:13
It does appear to be the case that the client is wrongly parsing some text, but I have not yet debugged anything to find out why. Given that personal text is displayed fine, this _should_ be fixable

**Comment by Marcus101RR** [comment] 2016-01-28 17:46
My thoughts were that this: 					NetMessage.SendData((int)PacketTypes.ChatText, -1, args.Who, text, args.Who, tsplr.Group.R, tsplr.Group.G, tsplr.Group.B);
					NetMessage.SendData((int)PacketTypes.PlayerInfo, -1, -1, name, args.Who, 0, 0, 0, 0);

Handles the Chat Above Heads...

Meanwhile, this handles the sending to others and the player himself?

					string msg = String.Format("<{0}> {1}",
						String.Format(Config.ChatAboveHeadsFormat, tsplr.Group.Name, tsplr.Group.Prefix, tsplr.Name, tsplr.Group.Suffix),
						text);

					tsplr.SendMessage(msg, tsplr.Group.R, tsplr.Group.G, tsplr.Group.B);

					TSPlayer.Server.SendMessage(msg, tsplr.Group.R, tsplr.Group.G, tsplr.Group.B);

**Comment by WhiteXZ** [comment] 2016-01-28 23:05
Correct

**Comment by Marcus101RR** [comment] 2016-01-31 00:53
So here is my analysis:
tsplr.SendMessage(msg, tsplr.Group.R, tsplr.Group.G, tsplr.Group.B);
This causes you to see your own message, with successful tags while ChatAboveHeads.

TSPlayer.Server.SendMessage(msg, tsplr.Group.R, tsplr.Group.G, tsplr.Group.B);
This I believe, is what sends the chat message on the console, and possibly also the message itself to others on the server. Since I Peeked the Definition, it seems to use the Chat packet...

This is where it all goes wrong. Maybe use TShock's chat sending instead?

**Comment by Marcus101RR** [comment] 2016-01-31 03:32
UPDATE: I have come to the conclusion, that it is infact: NetMessage.SendData((int)PacketTypes.ChatText, -1, args.Who, text, args.Who, tsplr.Group.R, tsplr.Group.G, tsplr.Group.B);

this cannot be modified, at least not from my stand point. This is what causes everyone to see the screwed up prefixes...

**Comment by ProfessorXZ** [comment] 2016-08-11 19:41
Duplicate of #1104. We've already come to the conclusion why this is happening but let's just make it clear one more time: The reason the sender parses text properly is that the ChatText packet is handled differently. `TSPlayer.SendMessage` methods pass in `255` as the ID of the player that sent the packet, this results in a blank line which then allows us to modify text as we want. As we can see in code Marcus posted above, we pass in the player's whoAmI as the ID of the player that sent the packet, which breaks chat tags. Ofcourse, if we don't pass in the player's whoAmI the chat doesn't show above the player's head. I don't see a way to work around this as of now, we can continue the discussion in Slack if needed.

**Comment by nicatronTg** [comment] 2016-10-11 01:11
Closing because this issue duplicates #1104.

**Closed by nicatronTg** 2016-10-11 01:11 UTC
Labels: Confirmed Issue, Improvement
