### ISSUE TITLE
Wrong item showing for others

### ISSUE THREAD

**Issue by defran** [NyxStudios/TShock#1008] opened 2015-07-14 18:36 UTC
So we noticed thatt some items epople use are shown wrong to others. Example I used Picksaw and others told me they saw a Copper pick. We noticed this problem with many items but I don't know how much of the items are affected.

**Comment by Kojirremer** [comment] 2015-07-20 04:36
Yes, I noticed as well using the latest stable build. When another player used the razorblade typhoon, she was shown swinging a copper pickaxe while shooting the razorblade projectiles, and when using the razorpine she shot the needles from A CARROT. Hilarious XD

**Comment by WhiteXZ** [comment] 2015-07-20 05:02
This is likely a packet or handler issue. Please test if this occurs without TShockAPI.dll in ServerPlugins

**Comment by Patrikkk** [comment] 2015-07-27 18:36
Tested on latest with both mentioned items. (Local server, opened 2 clients)
Both items behaved fine. .-. weird

**Comment by tlworks** [comment] 2016-06-29 16:36
Basically happens with almost every weapon, especially the ones which shoot projectiles.

**Comment by nicatronTg** [comment] 2016-08-28 14:25
This issue has been kept in favor of #1031 which duplicates it.

**Comment by nicatronTg** [comment] 2016-10-11 01:38
Thoughts on this anyone? Still relevant with Orion or should it be fixed in the API? Or is this just an API only problem?

**Comment by nicatronTg** [comment] 2016-10-11 01:39
I guess cc @WhiteXZ?

**Comment by tylerjwatson** [comment] 2016-10-11 01:46
I think it's a regression caused by optimising The syncPlayers function sending millions of packets. One of the big problems is that it was spamming everyone's inventory to everyone else. It's possible that the game relied on this and in some rare cases inventories go out of sync

**Comment by nicatronTg** [comment] 2016-10-11 01:56
@tylerjwatson so Orion or API?

**Comment by Patrikkk** [comment] 2016-10-11 09:43
Ah right. Tyler is most probably correct and this issue has been fixed around 1.3 in TSAPI.
I've not hear anyone run inot this issue since so we might as well close it

**Closed** 2016-10-11 15:46 UTC
Labels: Confirmed Issue, Unable To Reproduce
