### ISSUE TITLE
Invisible monsters and bombs

### ISSUE THREAD

**Issue by andry-dev** [NyxStudios/TShock#1147] opened 2015-12-30 20:58 UTC
TShock version: 4.3.11 and 4.3.9

*I* can't reproduce the bug, this only happens to the people who joins the server

Basically, there's a chance that killing a mob don't actually kill it and it become invisible

The mob, once invisible, continue to live until it's killed a second time (so it can deal damage)

I know this problem can be sorted as "network issue" (like abnormal ping), but it's not:
* Tested with both vanilla server and TShock, only happens on TShock
* All test were done on the same machine (which was rebooted few times)
* Ping was regular, both for the host (~50ms) and for the average client (~45ms, the min was 25ms, the max was 75ms)
* Router was rebooted few times

Me, the host, can't reproduce the problem because, for me, the mobs works just fine; So I can't provide any video or screenshot :/

The other issue is that even bombs, granades and dynamites are invisible when thrown from other players (and this was fixed [before](https://github.com/NyxStudios/TShock/issues/1095))

[config.json here](http://pastebin.com/echj2T6z), it's possible that some setting causes problems

Thank you for your time

**Comment by tylerjwatson** [comment] 2015-12-30 22:43
Invisible bombs were fixed in a recent version of bamboo. You will need to run the unstable builds to get these fixes as there hasn't been a release since then, yet.

**Comment by tylerjwatson** [comment] 2015-12-30 22:45
Never heard of invisible mobs, though. If you can make a reproduce case on the latest bamboo builds, I'll look into it.

**Comment by andry-dev** [comment] 2015-12-31 01:05
Tested with [#575](http://direct.tshock.co:8085/browse/TERRA-TSHOCK-575) from bamboo, invisible bombs are indeed fixed, but there's still the problem with mobs

It seems that it happens randomly though

Tomorrow me and my friends will be away because of the New Year, but once I can get someone to record it, I'll forward the video to you

**Comment by tylerjwatson** [comment] 2015-12-31 03:14
I appreciate the effort, but videos aren't useful to a dev team. You're better off trying to find a strong reproduce case so we can reproduce it and fix it.

**Comment by Marcus101RR** [comment] 2016-01-16 18:36
I can confirm the bug, but i'll correct it: They don't go invisible (at least not for me). As any user even the owner, killing a mob causes it do make the death sound, explode with gore, but it comes back to life once more and then a second time dies. I wonder if this issue has something to do with lag:
- Not enough RAM
- Not enough CPU?

Best way to reproduce this:
- 10-20 Players Online
- Pumpkin Moon/Frost Moon Wave 10+

You can watch best with StarDust Minions and Dragon killing the mobs and seeing the Dragon target the same mob twice because it didn't die.

**Comment by WhiteXZ** [comment] 2016-06-14 15:00
Tentatively closing

**Closed by WhiteXZ** 2016-06-14 15:00 UTC
Labels: Bug?, Needs Investigation
