### ISSUE TITLE
NPC/Mobs Despawning and Vitamins 

### ISSUE THREAD

**Issue by zevvex** [NyxStudios/TShock#1289] opened 2016-09-25 15:02 UTC
TShock 4.3.18 for Terraria 1.3.3.2 (API v1.24)
On expert mode, corrupt world, SSC off:

Seems like every mob drops vitamins at the moment, Wyverns despawn rather often in combat and warp around, one of the twins despawned randomly offscreen after 50%, random NPCS despawn regularly (no death reported).

This part isnt that important may have even been fixed:
I never bothered to repost before about it but if anyone remembers i posted long ago here while farming on previous versions of tshock for the ankh charm/shield, back when there was some of the parts blindfold etc never spawning. Anyway it wasnt fully fixed after that im 99% sure that whoever fixed it forgot to add code for it to double its drop chance in expert mode at that time. it may still have half drop rates as they should in expert mode & so might whatever else there was that was fixed like that id figure id mention it since someone will be looking into the vitamins nonsense (unless the rates were fixed more recently havent replayed in awhile) thanks!
Edit: To be clear there hasnt been anything not dropping yet, just would like to have that checked i went back and checked old post it was megaphones and blindfolds that were fixed back then (but still seem to drop far more rarely in expert mode than other parts, unless its just insanely bad luck) thanks again.

**Comment by daredev** [comment] 2016-09-25 21:16
Can confirm. On my medium corruption map, softcore (?) Wyverns are vanishing as well. Also, I had the same problem with Skeleton Prime.

**Comment by CandiedFedora** [comment] 2016-09-25 22:35
Can confirm too, got a lot of Vitamins by killing random mobs.

**Comment by CandiedFedora** [comment] 2016-09-25 23:07
Here are 2 videos of the issues,
Vitamins: https://www.youtube.com/watch?v=zpXBzCBEioQ
Wyvern: https://www.youtube.com/watch?v=riOZD80Q-BU

**Comment by Smelltastic** [comment] 2016-09-26 00:06
I also noticed the Vitamins issue, but it doesn't appear to happen with everything. It definitely happens with the moon pillar enemies though, which aren't supposed to drop anything at all, which makes me wonder if it has to do specifically with enemies that don't normally have any drops.

It also seems to happn even if you rename the ServerPlugins folder and move everything out other than TerrariraServer.exe, impying it's an issue with the modded exe, and it doesn't happen with the current vanilla server as pulled from my Steam folder.

**Comment by CandiedFedora** [comment] 2016-09-26 16:24
Found a temporary fix for this, just ban the item till this is fixed or unban it when you need to farm it.

**Comment by killerbonzai** [comment] 2016-09-27 06:37
I have gotten them from all kind of enimies.. playing hardmode expert..
There are things that I have had a much harder time getting though..
Killed hundreds of the hardmode dungeon blue skeletons to get armor polish.. yet nothing.. could be really bad luck.. but since it's on expert there should be 2% chance right? so after 300 i should have gotten at least one... seems like some REALLY bad luck or something else is wrong with drops..

**Comment by ProfessorXZ** [comment] 2016-10-02 20:45
Wyvern despawns is a known issues, and was reported a lot before, but thank you for reporting. I'll look into fixing that a bit later. The Vitamins issues on the other hand was not reported yet. @zevvex @daredev @CandiedFedora @Smelltastic @killerbonzai I believe the Vitamins issues should be fixed now, but I'd like you to test this to confirm: https://www.dropbox.com/s/c27w94mrzpgj3nl/TerrariaServer.exe?dl=0 . I've already built the file so you should be able to replace the current TerrariaServer.exe and run it without any problems. Here is a link to the commit I built it against: [4599ee7](https://github.com/ProfessorXZ/TerrariaAPI-Server/commit/4599ee7a82e22f162f110956a49d55acb502b737) If you can confirm this is no longer an issues it will be fixed in the next release.

**Comment by daredev** [comment] 2016-10-02 22:05
@ProfessorXZ testing it right now. I spawned the same 5x200 pirate mobs. No Vitamin was dropped. So seems that it fixed it, **however**, I haven't tested it against any other mobs yet.

**Comment by nicatronTg** [comment] 2016-10-04 09:20
Testing 4599ee7a82e22f162f110956a49d55acb502b737 manually worked for me. Normal behavior with vitamin drops. I believe @WhiteXZ is testing this in a more automated fashion.

**Comment by nicatronTg** [comment] 2016-10-04 09:24
Cherry-picked https://github.com/ProfessorXZ/TerrariaAPI-Server/commit/4599ee7a82e22f162f110956a49d55acb502b737 as https://github.com/NyxStudios/TerrariaAPI-Server/commit/28badfb654d0e14d228286cfe62738d2be6e7f47

```Kurisu 福 ~/Development
525 ◯ : git clone git@github.com:NyxStudios/TerrariaAPI-Server.git
Cloning into 'TerrariaAPI-Server'...
remote: Counting objects: 5516, done.
remote: Compressing objects: 100% (103/103), done.
remote: Total 5516 (delta 22), reused 0 (delta 0), pack-reused 5410
Receiving objects: 100% (5516/5516), 20.11 MiB | 6.50 MiB/s, done.
Resolving deltas: 100% (3878/3878), done.
Checking connectivity... done.

Kurisu 福 ~/Development
526 ◯ : cd TerrariaAPI-Server

Kurisu 福 ~/Development/TerrariaAPI-Server ➤ 8afd8a7|general-devel✓
527 ± : git remote add professorx https://github.com/ProfessorXZ/TerrariaAPI-Server.git          [5h42m]

Kurisu 福 ~/Development/TerrariaAPI-Server ➤ 8afd8a7|general-devel✓
528 ± : git fetch professorx                                                                     [5h42m]
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/ProfessorXZ/TerrariaAPI-Server
 * [new branch]      crash-reporter -> professorx/crash-reporter
 * [new branch]      general-devel -> professorx/general-devel
 * [new branch]      master     -> professorx/master
 * [new branch]      sendq      -> professorx/sendq

Kurisu 福 ~/Development/TerrariaAPI-Server ➤ 8afd8a7|general-devel✓
529 ± : git cherry-pick 4599ee7a82e22f162f110956a49d55acb502b737                                 [5h43m]
[general-devel 28badfb] Should fix the vitamin issue
 Author: ProfessorXZ <ssbiljan@gmail.com>
 Date: Sun Oct 2 22:29:23 2016 +0200
 1 file changed, 1 deletion(-)

Kurisu 福 ~/Development/TerrariaAPI-Server ➤ 28badfb|general-devel✓
530 ± : git push origin general-devel                                                        [1d12h52m]!
Counting objects: 4, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 477 bytes | 0 bytes/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To git@github.com:NyxStudios/TerrariaAPI-Server.git
   8afd8a7..28badfb  general-devel -> general-devel```

**Comment by WhiteXZ** [comment] 2016-10-04 09:24
https://github.com/ProfessorXZ/TerrariaAPI-Server/commit/4599ee7a82e22f162f110956a49d55acb502b737 seems to fix vitamin drops for corruptors, but not floaty gross

**Comment by nicatronTg** [comment] 2016-10-04 09:43
Just to clarify for the future: the problem with https://github.com/NyxStudios/TerrariaAPI-Server/commit/28badfb654d0e14d228286cfe62738d2be6e7f47 now is broken drop rates for some monsters. Likely requires rebuilding the drop case/switch stuff because some decompiler mess has created a lot of problems in NPC.cs.

**Comment by nicatronTg** [comment] 2016-10-04 09:43
(So the problem before was too many vitamins, now the problem is zero)

**Comment by nicatronTg** [comment] 2016-10-04 10:11
Per @WhiteXZ: https://github.com/NyxStudios/TerrariaAPI-Server/commit/eb5261cc7dc51c1550558f7acd97687982d617ae should fix all of the vitamin issues.

**Closed** 2016-10-07 07:20 UTC
Labels: Confirmed Issue, Needs Investigation
